---
- hosts: localhost
  gather_facts: false
  vars:
  - size: 1000000
  tasks:
    - command: du -sk ./test.sql
      register: folder_size_raw
    - set_fact:
        folder_size: "{{ folder_size_raw.stdout.split()[0] }}"
    - debug:
        msg: "{{ folder_size }}"
      when:
      - " folder_size|int  > 1000000"
